services:
  worker:
    build: .
    environment:
      SUPABASE_URL: http://supabase:8000
      SUPABASE_KEY: supabase_key
      TEXTURE_PRIVATE_KEY: |
        -----BEGIN PRIVATE KEY-----
        YOUR_PRIVATE_KEY
        -----END PRIVATE KEY-----
    ports:
      - "8787:8787"
    depends_on:
      - supabase
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  supabase:
    image: supabase/supabase-dev:latest
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: supabase
      DB_PORT: 5432
      DB_SCHEMA: public
    ports:
      - "54321:8000"
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  db:
    image: postgres:15
    command:
      - postgres
      - -c
      - wal_level=logical
    environment:
      POSTGRES_PASSWORD: supabase
    volumes:
      - supabase-db:/var/lib/postgresql/data
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  supabase-db:
